server:
  port: 8080
  servlet:    context-path: /
spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/tma
  jpa:
    hibernate:      ddl-auto: none
    